// Generated by Extensions/scripts/build.mjs from reviewed bundled.json. Do not edit.
nonisolated enum BundledExtensionResources {
    static let entries: [(manifestJSON: String, javaScript: String)] = [
        (manifestJSON: #"""
{"id":"dev.midoku.mangadex","name":"MangaDex","version":"0.2.1","contractVersion":2,"domains":["api.mangadex.org","mangadex.org","uploads.mangadex.org","*.mangadex.network"],"capabilities":["search","feeds","details","chapters","pages","filters"]}
"""#, javaScript: #"""
var MidokuExtension = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sources/dev.midoku.mangadex/index.ts
  var index_exports = {};
  __export(index_exports, {
    default: () => index_default
  });

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sdk/index.ts
  function defineExtension(extension) {
    return Object.freeze(extension);
  }

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sources/dev.midoku.mangadex/filters.ts
  var options = (values) => values.map(([id, title]) => ({ id, title }));
  var languages = options([
    ["en", "English"],
    ["ja", "Japanese"],
    ["ko", "Korean"],
    ["zh", "Chinese (Simplified)"],
    ["zh-hk", "Chinese (Traditional)"],
    ["es", "Spanish"],
    ["es-la", "Spanish (Latin America)"],
    ["pt-br", "Portuguese (Brazil)"],
    ["pt", "Portuguese"],
    ["fr", "French"],
    ["de", "German"],
    ["it", "Italian"],
    ["ru", "Russian"],
    ["uk", "Ukrainian"],
    ["pl", "Polish"],
    ["tr", "Turkish"],
    ["ar", "Arabic"],
    ["bn", "Bengali"],
    ["hi", "Hindi"],
    ["id", "Indonesian"],
    ["ms", "Malay"],
    ["th", "Thai"],
    ["vi", "Vietnamese"],
    ["tl", "Filipino"],
    ["my", "Burmese"],
    ["fa", "Persian"],
    ["he", "Hebrew"],
    ["ro", "Romanian"],
    ["hu", "Hungarian"],
    ["cs", "Czech"],
    ["sk", "Slovak"],
    ["bg", "Bulgarian"],
    ["el", "Greek"],
    ["nl", "Dutch"],
    ["sv", "Swedish"],
    ["da", "Danish"],
    ["no", "Norwegian"],
    ["fi", "Finnish"],
    ["sr", "Serbian"],
    ["hr", "Croatian"]
  ]);
  function filter(id, title, choices, defaults = [], kind = "multiple", required = false) {
    return { id, title, kind, options: choices, defaults, scopes: ["search", "feed"], required };
  }
  var staticFilters = [
    { ...filter("sort", "Sort", options([
      ["relevance:desc", "Best match"],
      ["followedCount:desc", "Most followed"],
      ["rating:desc", "Highest rated"],
      ["latestUploadedChapter:desc", "Latest updates"],
      ["createdAt:desc", "Recently added"],
      ["title:asc", "Title A\u2013Z"],
      ["title:desc", "Title Z\u2013A"],
      ["year:desc", "Newest publication"]
    ]), ["relevance:desc"], "single", true), scopes: ["search"] },
    filter("language", "Chapter language", languages, ["en"], "single", true),
    filter("status", "Publication status", options([
      ["ongoing", "Ongoing"],
      ["completed", "Completed"],
      ["hiatus", "Hiatus"],
      ["cancelled", "Cancelled"]
    ])),
    filter("demographic", "Demographic", options([
      ["shounen", "Shounen"],
      ["shoujo", "Shoujo"],
      ["seinen", "Seinen"],
      ["josei", "Josei"],
      ["none", "Unspecified"]
    ])),
    filter("originalLanguage", "Original language", languages),
    filter("rating", "Content rating", options([
      ["safe", "Safe"],
      ["suggestive", "Suggestive"],
      ["erotica", "Erotica"],
      ["pornographic", "Pornographic"]
    ]), ["safe", "suggestive"], "multiple", true),
    filter("includedTagsMode", "Match included tags", options([["AND", "All selected tags"], ["OR", "Any selected tag"]]), ["AND"], "single", true),
    filter("excludedTagsMode", "Exclude titles matching", options([["OR", "Any excluded tag"], ["AND", "All excluded tags"]]), ["OR"], "single", true)
  ];
  function tagFilters(tags) {
    return [filter("includedTags", "Include tags", tags), filter("excludedTags", "Exclude tags", tags)];
  }
  function searchParameters(values = {}, feedSort) {
    if (!values || typeof values !== "object" || Array.isArray(values)) throw new Error("Invalid filters");
    const known = /* @__PURE__ */ new Set([...staticFilters.map((filter2) => filter2.id), "includedTags", "excludedTags"]);
    if (Object.keys(values).some((key) => !known.has(key))) throw new Error("Unknown filter");
    const selected = {};
    for (const definition of staticFilters) {
      const value = values[definition.id] ?? definition.defaults;
      if (!Array.isArray(value) || new Set(value).size !== value.length || definition.required && value.length === 0 || definition.kind === "single" && value.length > 1 || value.some((id) => !definition.options.some((option) => option.id === id))) throw new Error("Invalid filter selection");
      selected[definition.id] = value;
    }
    const result = [["hasAvailableChapters", "true"]];
    for (const [key, parameter] of [
      ["language", "availableTranslatedLanguage[]"],
      ["rating", "contentRating[]"],
      ["status", "status[]"],
      ["demographic", "publicationDemographic[]"],
      ["originalLanguage", "originalLanguage[]"]
    ]) {
      for (const value of selected[key]) result.push([parameter, value]);
    }
    for (const key of ["includedTags", "excludedTags"]) {
      const ids = values[key] ?? [];
      if (!Array.isArray(ids) || ids.length > 100 || ids.some((id) => typeof id !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id))) throw new Error("Invalid tag selection");
      for (const id of ids) result.push([key + "[]", id]);
      result.push([key + "Mode", selected[key + "Mode"][0]]);
    }
    const [sort, direction] = (feedSort ?? selected.sort[0]).split(":");
    result.push([`order[${sort}]`, direction]);
    return result;
  }

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sources/dev.midoku.mangadex/index.ts
  var api = "https://api.mangadex.org";
  var referer = "https://mangadex.org/";
  var pageSize = 20;
  var chapterPageSize = 100;
  var maximumResults = 1e4;
  var language = "en";
  var uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
  function object(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected object");
    return value;
  }
  function text(value) {
    if (typeof value !== "string" || !value.trim()) throw new Error("Missing text");
    return value;
  }
  function optionalText(value) {
    if (value == null || value === "") return null;
    return text(value);
  }
  function integer(value) {
    if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) throw new Error("Invalid count");
    return value;
  }
  function uuid(value) {
    const id = text(value);
    if (!uuidPattern.test(id)) throw new Error("Invalid MangaDex ID");
    return id;
  }
  function segment(value) {
    const part = text(value);
    if (part === "." || part === ".." || /[\\/%?#\s]/.test(part)) throw new Error("Invalid resource path");
    return encodeURIComponent(part);
  }
  function offsetFrom(cursor) {
    if (cursor == null) return 0;
    if (!/^(0|[1-9][0-9]{0,3})$/.test(cursor)) throw new Error("Invalid MangaDex cursor");
    return Number(cursor);
  }
  function localized(maps, preferred) {
    for (const map of maps) {
      for (const value of Object.values(map)) {
        if (typeof value !== "string") throw new Error("Invalid localized text");
      }
    }
    for (const locale of preferred) {
      for (const map of maps) {
        const value = map[locale];
        if (typeof value === "string" && value.trim()) return value;
      }
    }
    for (const map of maps) {
      for (const locale of Object.keys(map).sort()) {
        const value = map[locale];
        if (value.trim()) return value;
      }
    }
    return null;
  }
  function relationships(value) {
    if (!Array.isArray(value.relationships)) throw new Error("Missing relationships");
    return value.relationships.map(object);
  }
  function entity(value, type) {
    const result = object(value);
    if (result.type !== type) throw new Error("Unexpected entity type");
    uuid(result.id);
    object(result.attributes);
    return result;
  }
  function summary(value) {
    const manga = entity(value, "manga");
    const attributes = object(manga.attributes);
    const maps = [object(attributes.title)];
    if (attributes.altTitles !== void 0) {
      if (!Array.isArray(attributes.altTitles)) throw new Error("Invalid alternative titles");
      maps.push(...attributes.altTitles.map(object));
    }
    const title = localized(maps, [language, "ja-ro", optionalText(attributes.originalLanguage) ?? ""]);
    if (!title) throw new Error("Missing manga title");
    const cover = relationships(manga).find((item) => item.type === "cover_art");
    const fileName = cover?.attributes == null ? null : optionalText(object(cover.attributes).fileName);
    const id = uuid(manga.id);
    return {
      id,
      title,
      coverURL: fileName === null ? null : `https://uploads.mangadex.org/covers/${id}/${segment(fileName)}.256.jpg`
    };
  }
  async function get(host, path, parameters = []) {
    const query = parameters.map(([key, value]) => encodeURIComponent(key) + "=" + encodeURIComponent(value)).join("&");
    const response = await host.request({
      url: api + path + (query ? "?" + query : ""),
      headers: { Accept: "application/json", Referer: referer }
    });
    const result = object(JSON.parse(response.body));
    if (result.result !== "ok") throw new Error("MangaDex returned an API error");
    return result;
  }
  function collection(value, offset, limit) {
    if (value.response !== "collection" || !Array.isArray(value.data)) throw new Error("Missing collection");
    const actualLimit = integer(value.limit);
    const total = integer(value.total);
    if (integer(value.offset) !== offset || actualLimit < 1 || actualLimit > limit || value.data.length > actualLimit) {
      throw new Error("Invalid pagination metadata");
    }
    if (value.data.length === 0 && offset < total) throw new Error("Unexpected empty page");
    const next = offset + actualLimit;
    return { items: value.data, nextCursor: next < Math.min(total, maximumResults) ? String(next) : null };
  }
  function unique(items) {
    if (new Set(items.map((item) => item.id)).size !== items.length) throw new Error("Duplicate source ID");
    return items;
  }
  async function mangaPage(host, cursor, parameters) {
    const offset = offsetFrom(cursor);
    const limit = Math.min(pageSize, maximumResults - offset);
    const response = await get(host, "/manga", [
      ["limit", String(limit)],
      ["offset", String(offset)],
      ["includes[]", "cover_art"],
      ...parameters
    ]);
    const page = collection(response, offset, limit);
    const preferredChapterLanguage = parameters.find(([key]) => key === "availableTranslatedLanguage[]")?.[1] ?? language;
    return { items: unique(page.items.map((value) => ({ ...summary(value), preferredChapterLanguage }))), nextCursor: page.nextCursor };
  }
  function chapter(value, mangaID, ordinal, requestedLanguage) {
    const entry = entity(value, "chapter");
    const attributes = object(entry.attributes);
    const parent = relationships(entry).find((item) => item.type === "manga");
    if (!parent || uuid(parent.id) !== mangaID) throw new Error("Chapter belongs to another manga");
    if (attributes.isUnavailable !== void 0 && typeof attributes.isUnavailable !== "boolean") {
      throw new Error("Invalid chapter availability");
    }
    if (optionalText(attributes.externalUrl) !== null || attributes.isUnavailable === true || integer(attributes.pages) === 0) return null;
    const translatedLanguage = text(attributes.translatedLanguage);
    if (requestedLanguage && translatedLanguage !== requestedLanguage) return null;
    const number = optionalText(attributes.chapter);
    const volume = optionalText(attributes.volume);
    const fallback = number === null ? "Oneshot" : `Chapter ${number}`;
    const title = optionalText(attributes.title) ?? fallback;
    return {
      id: uuid(entry.id),
      title: volume === null ? title : `Vol. ${volume} \xB7 ${title}`,
      number,
      ordinal,
      language: translatedLanguage,
      volume,
      groups: relationships(entry).filter((item) => item.type === "scanlation_group" && item.attributes != null).map((item) => text(object(item.attributes).name))
    };
  }
  function imageBase(value) {
    const base = text(value).replace(/\/$/, "");
    const match = /^https:\/\/([a-z0-9.-]+)(?::443)?((?:\/[A-Za-z0-9._~-]+)*)$/.exec(base);
    const host = match?.[1];
    if (!host || !(host === "uploads.mangadex.org" || host.endsWith(".mangadex.network"))) {
      throw new Error("Unexpected MangaDex image host");
    }
    if (match[2].split("/").some((part) => part === "." || part === "..")) throw new Error("Invalid image base path");
    return base;
  }
  var index_default = defineExtension({
    async getSearchFilters(_, host) {
      const result = await get(host, "/manga/tag");
      if (!Array.isArray(result.data)) throw new Error("Missing tags");
      const tags = result.data.map((value) => {
        const tag = entity(value, "tag");
        return { id: uuid(tag.id), title: localized([object(object(tag.attributes).name)], [language]) ?? "Tag" };
      }).sort((a, b) => a.title.localeCompare(b.title));
      return [...staticFilters, ...tagFilters(unique(tags))];
    },
    async search({ query, cursor, filters }, host) {
      const parameters = searchParameters(filters);
      if (query.trim()) parameters.push(["title", query.trim()]);
      return mangaPage(host, cursor, parameters);
    },
    async getFeeds() {
      return [
        { id: "latest", title: "Latest updates" },
        { id: "popular", title: "Popular" },
        { id: "recent", title: "Recently added" }
      ];
    },
    async getFeedPage({ feedID, cursor, filters }, host) {
      const sort = feedID === "latest" ? "latestUploadedChapter" : feedID === "popular" ? "followedCount" : feedID === "recent" ? "createdAt" : null;
      if (!sort) throw new Error("Unknown MangaDex feed");
      return mangaPage(host, cursor, searchParameters(filters, `${sort}:desc`));
    },
    async getMangaDetails({ mangaID }, host) {
      uuid(mangaID);
      const response = await get(host, `/manga/${mangaID}`, [["includes[]", "cover_art"], ["includes[]", "author"], ["includes[]", "artist"]]);
      const manga = entity(response.data, "manga");
      if (manga.id !== mangaID) throw new Error("Manga ID mismatch");
      const attributes = object(manga.attributes);
      const names = (type) => relationships(manga).filter((item) => item.type === type && item.attributes != null).map((item) => text(object(item.attributes).name));
      const availableLanguages = attributes.availableTranslatedLanguages == null ? [language] : attributes.availableTranslatedLanguages.filter((value) => typeof value === "string" && /^[a-z-]{2,8}$/.test(value));
      const tags = attributes.tags == null ? [] : attributes.tags.map((value) => localized([object(object(object(value).attributes).name)], [language]) ?? "Tag");
      return {
        ...summary(manga),
        description: localized([object(attributes.description)], [language]) ?? "",
        authors: names("author"),
        artists: names("artist"),
        tags,
        status: optionalText(attributes.status),
        year: attributes.year == null ? null : String(integer(attributes.year)),
        availableLanguages: [...new Set(availableLanguages)].map((id) => ({ id, title: languages.find((option) => option.id === id)?.title ?? id })),
        defaultChapterLanguage: availableLanguages.includes(language) ? language : availableLanguages[0] ?? language,
        webURL: `https://mangadex.org/title/${mangaID}`
      };
    },
    async getChapterPage({ mangaID, cursor, language: selectedLanguage }, host) {
      uuid(mangaID);
      const chapterLanguage = selectedLanguage ?? language;
      if (!/^[a-z]{2}(-[a-z]{2,3})?$/.test(chapterLanguage)) throw new Error("Invalid chapter language");
      const offset = offsetFrom(cursor);
      const limit = Math.min(chapterPageSize, maximumResults - offset);
      const response = await get(host, `/manga/${mangaID}/feed`, [
        ["limit", String(limit)],
        ["offset", String(offset)],
        ["translatedLanguage[]", chapterLanguage],
        ["includes[]", "scanlation_group"],
        ["order[volume]", "asc"],
        ["order[chapter]", "asc"],
        ["order[createdAt]", "asc"],
        ["includeExternalUrl", "0"],
        ["includeUnavailable", "0"],
        ["includeEmptyPages", "0"],
        ["includeFutureUpdates", "0"],
        ["includeFuturePublishAt", "0"],
        ...["safe", "suggestive", "erotica", "pornographic"].map((value) => ["contentRating[]", value])
      ]);
      const page = collection(response, offset, limit);
      const items = page.items.map((value, index) => chapter(value, mangaID, offset + index, chapterLanguage)).filter((value) => value !== null);
      return { items: unique(items), nextCursor: page.nextCursor };
    },
    async getChapterPages({ mangaID, chapterID }, host) {
      uuid(mangaID);
      uuid(chapterID);
      const metadata = await get(host, `/chapter/${chapterID}`);
      if (object(metadata.data).id !== chapterID || chapter(metadata.data, mangaID, 0) === null) {
        throw new Error("Chapter is not readable");
      }
      const response = await get(host, `/at-home/server/${chapterID}`, [["forcePort443", "true"]]);
      const base = imageBase(response.baseUrl);
      const pages = object(response.chapter);
      const hash = segment(pages.hash);
      if (!Array.isArray(pages.data) || pages.data.length === 0 || pages.data.length > 2e3) {
        throw new Error("Missing chapter pages");
      }
      return pages.data.map((file, index) => ({
        id: `${chapterID}:${index + 1}`,
        url: `${base}/data/${hash}/${segment(file)}`,
        headers: { Referer: referer }
      }));
    }
  });
  return __toCommonJS(index_exports);
})();

"""#),
        (manifestJSON: #"""
{"id":"dev.midoku.comix","name":"Comix","version":"0.1.0","contractVersion":2,"domains":["comix.to","comix.ws","static.comix.to","*.wowpic2.store"],"capabilities":["search","feeds","details","chapters","pages","filters"],"browserRendering":true,"imageProcessing":"comix-v1"}
"""#, javaScript: #"""
var MidokuExtension = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sources/dev.midoku.comix/index.ts
  var index_exports = {};
  __export(index_exports, {
    default: () => index_default
  });

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sdk/index.ts
  function defineExtension(extension) {
    return Object.freeze(extension);
  }

  // midoku:/workspace/scratch/e7e7937cc129/midoku-work/Extensions/sources/dev.midoku.comix/index.ts
  var base = "https://comix.to";
  function id(value, chapter = false) {
    if (typeof value !== "string" || !(chapter ? /^[1-9][0-9]{0,14}$/ : /^[a-zA-Z0-9]{1,40}$/).test(value)) throw Error("Invalid Comix identity");
    return value;
  }
  function page(value) {
    if (value == null) return 1;
    if (!/^[1-9][0-9]{0,5}$/.test(value)) throw Error("Invalid cursor");
    return Number(value);
  }
  function object(value) {
    if (!value || typeof value !== "object" || Array.isArray(value)) throw Error("Invalid Comix response");
    return value;
  }
  function allowed(manga) {
    return ["safe", "suggestive"].includes(manga.contentRating ?? manga.content_rating);
  }
  function text(value) {
    return typeof value === "string" ? value.replace(/<[^>]*>/g, "").trim() : "";
  }
  function terms(value) {
    return Array.isArray(value) ? value.map((x) => text(x?.title)).filter(Boolean) : [];
  }
  function summary(manga) {
    object(manga);
    const title = text(manga.title);
    if (!title) throw Error("Missing title");
    return { id: id(manga.hid), title, coverURL: manga.poster?.medium ?? manga.poster?.large ?? manga.poster?.small ?? null, preferredChapterLanguage: "en" };
  }
  function script(operation, args) {
    return `(() => {
      const fail = value => { window.__midokuResult = JSON.stringify({midokuError:value}); };
      const xhrSend = XMLHttpRequest.prototype.send;
      XMLHttpRequest.prototype.send = function(...args) {
        this.addEventListener('load', () => { if (this.getResponseHeader('cf-mitigated') === 'challenge' ||
          ([403,503].includes(this.status) && /text\\/html/i.test(this.getResponseHeader('content-type') || '') && /cloudflare/i.test(this.responseText || ''))) fail('verification'); });
        return xhrSend.apply(this,args);
      };
      const run = async () => { try {
        const origin = new URL(document.baseURI).origin;
        const main = document.querySelector('script[src*="/main-"]');
        if (!main) throw Error('Website module missing');
        const moduleURL = new URL(main.getAttribute('src'), document.baseURI);
        if (moduleURL.origin !== origin) throw Error('Invalid module origin');
        const response = await fetch(moduleURL.href, {credentials:'include'});
        if (response.headers.get('cf-mitigated') === 'challenge') { fail('verification'); return; }
        const source = await response.text();
        const match = source.match(/from\\s*["']\\.\\/(env-[^"']+\\.js)["']/);
        if (!match) throw Error('Website API module missing');
        const envURL = new URL(match[1],moduleURL);
        if (envURL.origin !== origin) throw Error('Invalid API origin');
        const exports = await import(envURL.href);
        const values = Object.values(exports);
        const manga = values.find(x => x && typeof x.list === 'function' && typeof x.chapters === 'function' && typeof x.get === 'function');
        const http = values.find(x => x && typeof x.get === 'function' && typeof x.post === 'function' && typeof x.patch === 'function' && typeof x.delete === 'function' && !x.chapters && !x.interceptors);
        if (!manga) throw Error('Website API unavailable');
        const args = ${JSON.stringify(args)};
        let result;
        if (${JSON.stringify(operation)} === 'list') result = await manga.list(args);
        else {
          const entry = await manga.get(args.mangaID);
          if (!['safe','suggestive'].includes(entry.contentRating ?? entry.content_rating)) throw Error('Entry unavailable');
          if (${JSON.stringify(operation)} === 'details') result = entry;
          else if (${JSON.stringify(operation)} === 'chapters') result = await manga.chapters(args.mangaID,{page:args.page,limit:100,order:{number:'asc'}});
          else { if (!http) throw Error('Reader API unavailable'); result = await http.get('/chapters/' + args.chapterID);
            const parent = result.manga?.hid ?? result.mangaHid ?? result.manga_hid;
            if ((parent && parent !== args.mangaID) || (result.mangaId != null && entry.id != null && String(result.mangaId) !== String(entry.id))) throw Error('Chapter does not belong to entry');
          }
        }
        if (!window.__midokuResult) window.__midokuResult = JSON.stringify({result});
      } catch(e) { if (!window.__midokuResult) fail('extraction'); } };
      if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded',run,{once:true}); else run();
    })();`;
  }
  async function request(host, operation, args) {
    const response = await host.request({ url: base + "/browse", headers: { Accept: "text/html", Referer: base + "/" }, browserScript: script(operation, args) });
    return object(JSON.parse(response.body)).result;
  }
  function paginated(result, current) {
    object(result);
    if (!Array.isArray(result.items)) throw Error("Missing items");
    const meta = object(result.meta ?? result.pagination);
    const last = meta.lastPage ?? meta.last_page;
    if (meta.page !== current || !(Number.isInteger(last) && last >= current || typeof meta.hasNext === "boolean")) throw Error("Invalid pagination");
    const more = meta.hasNext === true || Number.isInteger(last) && current < last;
    return { items: result.items, nextCursor: more ? String(current + 1) : null };
  }
  var sortOptions = [{ id: "views_30d", title: "Popular" }, { id: "chapter_updated_at", title: "Recently updated" }, { id: "created_at", title: "Recently added" }];
  function parameters(query, cursor, filters, feed) {
    for (const key of Object.keys(filters ?? {})) if (key !== "sort") throw Error("Unknown filter");
    const sort = feed ?? filters?.sort?.[0] ?? "views_30d";
    if (!sortOptions.some((x) => x.id === sort) || filters?.sort && filters.sort.length !== 1) throw Error("Invalid sort");
    return { keyword: query.trim(), page: page(cursor), limit: 28, content_rating: ["safe", "suggestive"], order: { [sort]: "desc" } };
  }
  async function catalogue(host, params) {
    const result = paginated(await request(host, "list", params), params.page);
    return { ...result, items: result.items.filter(allowed).map(summary) };
  }
  var index_default = defineExtension({
    async getSearchFilters() {
      return [{ id: "sort", title: "Sort", kind: "single", options: sortOptions, defaults: ["views_30d"], scopes: ["search"], required: true }];
    },
    async getFeeds() {
      return sortOptions;
    },
    async search(input, host) {
      return catalogue(host, parameters(input.query, input.cursor, input.filters));
    },
    async getFeedPage(input, host) {
      return catalogue(host, parameters("", input.cursor, input.filters, input.feedID));
    },
    async getMangaDetails(input, host) {
      const value = object(await request(host, "details", { mangaID: id(input.mangaID) }));
      if (!allowed(value) || value.hid !== input.mangaID) throw Error("Entry unavailable");
      return {
        ...summary(value),
        description: text(value.synopsis),
        authors: terms(value.authors ?? value.author),
        artists: terms(value.artists ?? value.artist),
        status: text(value.status),
        year: value.year == null ? null : String(value.year),
        tags: [...terms(value.genres ?? value.genre), ...terms(value.tags ?? value.theme)],
        availableLanguages: [{ id: "en", title: "English" }],
        defaultChapterLanguage: "en",
        webURL: base + "/title/" + input.mangaID
      };
    },
    async getChapterPage(input, host) {
      if (input.language && input.language !== "en") throw Error("Unsupported chapter language");
      const current = page(input.cursor);
      const result = paginated(await request(host, "chapters", { mangaID: id(input.mangaID), page: current }), current);
      return { ...result, items: result.items.map((chapter, index) => {
        object(chapter);
        const number = typeof chapter.number === "number" && Number.isFinite(chapter.number) ? String(chapter.number) : null;
        return {
          id: id(String(chapter.id), true),
          title: text(chapter.name) || (number ? "Chapter " + number : "Chapter"),
          number,
          ordinal: (current - 1) * 100 + index,
          language: "en",
          groups: chapter.group?.name ? [text(chapter.group.name)] : [],
          volume: null,
          uploadedAt: null
        };
      }) };
    },
    async getChapterPages(input, host) {
      id(input.mangaID);
      id(input.chapterID, true);
      const result = object(await request(host, "pages", { mangaID: input.mangaID, chapterID: input.chapterID }));
      if (result.id != null && String(result.id) !== input.chapterID) throw Error("Chapter identity mismatch");
      const container = result.pages;
      const pages = Array.isArray(container) ? container : container?.items;
      if (!Array.isArray(pages) || !pages.length) throw Error("Chapter has no pages");
      return pages.map((item, index) => {
        object(item);
        if (typeof item.url !== "string" || !item.url) throw Error("Missing page URL");
        let url = /^https:/.test(item.url) ? item.url : (container.baseUrl ?? "").replace(/\/$/, "") + "/" + item.url.replace(/^\//, "");
        if (!/^https:\/\/[^\s]+$/.test(url)) throw Error("Invalid page URL");
        if ((item.s === 1 || item.scramble === true) && !/[?&]v3(?:&|$)/.test(url)) url += (url.includes("?") ? "&" : "?") + "v3";
        return { id: input.chapterID + ":" + index, url, headers: { Referer: base + "/" } };
      });
    }
  });
  return __toCommonJS(index_exports);
})();

"""#)
    ]
}
