// Generated by Extensions/scripts/build.mjs from reviewed bundled.json. Do not edit.
nonisolated enum BundledExtensionResources {
    static let entries: [(manifestJSON: String, javaScript: String)] = [
        (manifestJSON: #"""
{"id":"dev.midoku.mangadex","name":"MangaDex","version":"0.2.0","contractVersion":2,"domains":["api.mangadex.org","mangadex.org","uploads.mangadex.org","*.mangadex.network"],"capabilities":["search","feeds","details","chapters","pages","filters"]}
"""#, javaScript: #"""
var MidokuExtension = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sources/dev.midoku.mangadex/index.ts
  var index_exports = {};
  __export(index_exports, {
    default: () => index_default
  });

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sdk/index.ts
  function defineExtension(extension) {
    return Object.freeze(extension);
  }

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sources/dev.midoku.mangadex/filters.ts
  var options = (values) => values.map(([id, title]) => ({ id, title }));
  var languages = options([
    ["en", "English"],
    ["ja", "Japanese"],
    ["ko", "Korean"],
    ["zh", "Chinese (Simplified)"],
    ["zh-hk", "Chinese (Traditional)"],
    ["es", "Spanish"],
    ["es-la", "Spanish (Latin America)"],
    ["pt-br", "Portuguese (Brazil)"],
    ["pt", "Portuguese"],
    ["fr", "French"],
    ["de", "German"],
    ["it", "Italian"],
    ["ru", "Russian"],
    ["uk", "Ukrainian"],
    ["pl", "Polish"],
    ["tr", "Turkish"],
    ["ar", "Arabic"],
    ["bn", "Bengali"],
    ["hi", "Hindi"],
    ["id", "Indonesian"],
    ["ms", "Malay"],
    ["th", "Thai"],
    ["vi", "Vietnamese"],
    ["tl", "Filipino"],
    ["my", "Burmese"],
    ["fa", "Persian"],
    ["he", "Hebrew"],
    ["ro", "Romanian"],
    ["hu", "Hungarian"],
    ["cs", "Czech"],
    ["sk", "Slovak"],
    ["bg", "Bulgarian"],
    ["el", "Greek"],
    ["nl", "Dutch"],
    ["sv", "Swedish"],
    ["da", "Danish"],
    ["no", "Norwegian"],
    ["fi", "Finnish"],
    ["sr", "Serbian"],
    ["hr", "Croatian"]
  ]);
  function filter(id, title, choices, defaults = [], kind = "multiple", required = false) {
    return { id, title, kind, options: choices, defaults, scopes: ["search", "feed"], required };
  }
  var staticFilters = [
    { ...filter("sort", "Sort", options([
      ["relevance:desc", "Best match"],
      ["followedCount:desc", "Most followed"],
      ["rating:desc", "Highest rated"],
      ["latestUploadedChapter:desc", "Latest updates"],
      ["createdAt:desc", "Recently added"],
      ["title:asc", "Title A\u2013Z"],
      ["title:desc", "Title Z\u2013A"],
      ["year:desc", "Newest publication"]
    ]), ["relevance:desc"], "single", true), scopes: ["search"] },
    filter("language", "Chapter language", languages, ["en"], "single", true),
    filter("status", "Publication status", options([
      ["ongoing", "Ongoing"],
      ["completed", "Completed"],
      ["hiatus", "Hiatus"],
      ["cancelled", "Cancelled"]
    ])),
    filter("demographic", "Demographic", options([
      ["shounen", "Shounen"],
      ["shoujo", "Shoujo"],
      ["seinen", "Seinen"],
      ["josei", "Josei"],
      ["none", "Unspecified"]
    ])),
    filter("originalLanguage", "Original language", languages),
    filter("rating", "Content rating", options([
      ["safe", "Safe"],
      ["suggestive", "Suggestive"],
      ["erotica", "Erotica"],
      ["pornographic", "Pornographic"]
    ]), ["safe", "suggestive"], "multiple", true),
    filter("includedTagsMode", "Match included tags", options([["AND", "All selected tags"], ["OR", "Any selected tag"]]), ["AND"], "single", true),
    filter("excludedTagsMode", "Exclude titles matching", options([["OR", "Any excluded tag"], ["AND", "All excluded tags"]]), ["OR"], "single", true)
  ];
  function tagFilters(tags) {
    return [filter("includedTags", "Include tags", tags), filter("excludedTags", "Exclude tags", tags)];
  }
  function searchParameters(values = {}, feedSort) {
    if (!values || typeof values !== "object" || Array.isArray(values)) throw new Error("Invalid filters");
    const known = /* @__PURE__ */ new Set([...staticFilters.map((filter2) => filter2.id), "includedTags", "excludedTags"]);
    if (Object.keys(values).some((key) => !known.has(key))) throw new Error("Unknown filter");
    const selected = {};
    for (const definition of staticFilters) {
      const value = values[definition.id] ?? definition.defaults;
      if (!Array.isArray(value) || new Set(value).size !== value.length || definition.required && value.length === 0 || definition.kind === "single" && value.length > 1 || value.some((id) => !definition.options.some((option) => option.id === id))) throw new Error("Invalid filter selection");
      selected[definition.id] = value;
    }
    const result = [["hasAvailableChapters", "true"]];
    for (const [key, parameter] of [
      ["language", "availableTranslatedLanguage[]"],
      ["rating", "contentRating[]"],
      ["status", "status[]"],
      ["demographic", "publicationDemographic[]"],
      ["originalLanguage", "originalLanguage[]"]
    ]) {
      for (const value of selected[key]) result.push([parameter, value]);
    }
    for (const key of ["includedTags", "excludedTags"]) {
      const ids = values[key] ?? [];
      if (!Array.isArray(ids) || ids.length > 100 || ids.some((id) => typeof id !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id))) throw new Error("Invalid tag selection");
      for (const id of ids) result.push([key + "[]", id]);
      result.push([key + "Mode", selected[key + "Mode"][0]]);
    }
    const [sort, direction] = (feedSort ?? selected.sort[0]).split(":");
    result.push([`order[${sort}]`, direction]);
    return result;
  }

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sources/dev.midoku.mangadex/index.ts
  var api = "https://api.mangadex.org";
  var referer = "https://mangadex.org/";
  var pageSize = 20;
  var chapterPageSize = 100;
  var maximumResults = 1e4;
  var language = "en";
  var uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
  function object(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected object");
    return value;
  }
  function text(value) {
    if (typeof value !== "string" || !value.trim()) throw new Error("Missing text");
    return value;
  }
  function optionalText(value) {
    if (value == null || value === "") return null;
    return text(value);
  }
  function integer(value) {
    if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) throw new Error("Invalid count");
    return value;
  }
  function uuid(value) {
    const id = text(value);
    if (!uuidPattern.test(id)) throw new Error("Invalid MangaDex ID");
    return id;
  }
  function segment(value) {
    const part = text(value);
    if (part === "." || part === ".." || /[\\/%?#\s]/.test(part)) throw new Error("Invalid resource path");
    return encodeURIComponent(part);
  }
  function offsetFrom(cursor) {
    if (cursor == null) return 0;
    if (!/^(0|[1-9][0-9]{0,3})$/.test(cursor)) throw new Error("Invalid MangaDex cursor");
    return Number(cursor);
  }
  function localized(maps, preferred) {
    for (const map of maps) {
      for (const value of Object.values(map)) {
        if (typeof value !== "string") throw new Error("Invalid localized text");
      }
    }
    for (const locale of preferred) {
      for (const map of maps) {
        const value = map[locale];
        if (typeof value === "string" && value.trim()) return value;
      }
    }
    for (const map of maps) {
      for (const locale of Object.keys(map).sort()) {
        const value = map[locale];
        if (value.trim()) return value;
      }
    }
    return null;
  }
  function relationships(value) {
    if (!Array.isArray(value.relationships)) throw new Error("Missing relationships");
    return value.relationships.map(object);
  }
  function entity(value, type) {
    const result = object(value);
    if (result.type !== type) throw new Error("Unexpected entity type");
    uuid(result.id);
    object(result.attributes);
    return result;
  }
  function summary(value) {
    const manga = entity(value, "manga");
    const attributes = object(manga.attributes);
    const maps = [object(attributes.title)];
    if (attributes.altTitles !== void 0) {
      if (!Array.isArray(attributes.altTitles)) throw new Error("Invalid alternative titles");
      maps.push(...attributes.altTitles.map(object));
    }
    const title = localized(maps, [language, "ja-ro", optionalText(attributes.originalLanguage) ?? ""]);
    if (!title) throw new Error("Missing manga title");
    const cover = relationships(manga).find((item) => item.type === "cover_art");
    const fileName = cover?.attributes == null ? null : optionalText(object(cover.attributes).fileName);
    const id = uuid(manga.id);
    return {
      id,
      title,
      coverURL: fileName === null ? null : `https://uploads.mangadex.org/covers/${id}/${segment(fileName)}.256.jpg`
    };
  }
  async function get(host, path, parameters = []) {
    const query = parameters.map(([key, value]) => encodeURIComponent(key) + "=" + encodeURIComponent(value)).join("&");
    const response = await host.request({
      url: api + path + (query ? "?" + query : ""),
      headers: { Accept: "application/json", Referer: referer }
    });
    const result = object(JSON.parse(response.body));
    if (result.result !== "ok") throw new Error("MangaDex returned an API error");
    return result;
  }
  function collection(value, offset, limit) {
    if (value.response !== "collection" || !Array.isArray(value.data)) throw new Error("Missing collection");
    const actualLimit = integer(value.limit);
    const total = integer(value.total);
    if (integer(value.offset) !== offset || actualLimit < 1 || actualLimit > limit || value.data.length > actualLimit) {
      throw new Error("Invalid pagination metadata");
    }
    if (value.data.length === 0 && offset < total) throw new Error("Unexpected empty page");
    const next = offset + actualLimit;
    return { items: value.data, nextCursor: next < Math.min(total, maximumResults) ? String(next) : null };
  }
  function unique(items) {
    if (new Set(items.map((item) => item.id)).size !== items.length) throw new Error("Duplicate source ID");
    return items;
  }
  async function mangaPage(host, cursor, parameters) {
    const offset = offsetFrom(cursor);
    const limit = Math.min(pageSize, maximumResults - offset);
    const response = await get(host, "/manga", [
      ["limit", String(limit)],
      ["offset", String(offset)],
      ["includes[]", "cover_art"],
      ...parameters
    ]);
    const page = collection(response, offset, limit);
    const preferredChapterLanguage = parameters.find(([key]) => key === "availableTranslatedLanguage[]")?.[1] ?? language;
    return { items: unique(page.items.map((value) => ({ ...summary(value), preferredChapterLanguage }))), nextCursor: page.nextCursor };
  }
  function chapter(value, mangaID, ordinal, requestedLanguage) {
    const entry = entity(value, "chapter");
    const attributes = object(entry.attributes);
    const parent = relationships(entry).find((item) => item.type === "manga");
    if (!parent || uuid(parent.id) !== mangaID) throw new Error("Chapter belongs to another manga");
    if (attributes.isUnavailable !== void 0 && typeof attributes.isUnavailable !== "boolean") {
      throw new Error("Invalid chapter availability");
    }
    if (optionalText(attributes.externalUrl) !== null || attributes.isUnavailable === true || integer(attributes.pages) === 0) return null;
    const translatedLanguage = text(attributes.translatedLanguage);
    if (requestedLanguage && translatedLanguage !== requestedLanguage) return null;
    const number = optionalText(attributes.chapter);
    const volume = optionalText(attributes.volume);
    const fallback = number === null ? "Oneshot" : `Chapter ${number}`;
    const title = optionalText(attributes.title) ?? fallback;
    return {
      id: uuid(entry.id),
      title: volume === null ? title : `Vol. ${volume} \xB7 ${title}`,
      number,
      ordinal,
      language: translatedLanguage,
      groups: relationships(entry).filter((item) => item.type === "scanlation_group" && item.attributes != null).map((item) => text(object(item.attributes).name))
    };
  }
  function imageBase(value) {
    const base = text(value).replace(/\/$/, "");
    const match = /^https:\/\/([a-z0-9.-]+)(?::443)?((?:\/[A-Za-z0-9._~-]+)*)$/.exec(base);
    const host = match?.[1];
    if (!host || !(host === "uploads.mangadex.org" || host.endsWith(".mangadex.network"))) {
      throw new Error("Unexpected MangaDex image host");
    }
    if (match[2].split("/").some((part) => part === "." || part === "..")) throw new Error("Invalid image base path");
    return base;
  }
  var index_default = defineExtension({
    async getSearchFilters(_, host) {
      const result = await get(host, "/manga/tag");
      if (!Array.isArray(result.data)) throw new Error("Missing tags");
      const tags = result.data.map((value) => {
        const tag = entity(value, "tag");
        return { id: uuid(tag.id), title: localized([object(object(tag.attributes).name)], [language]) ?? "Tag" };
      }).sort((a, b) => a.title.localeCompare(b.title));
      return [...staticFilters, ...tagFilters(unique(tags))];
    },
    async search({ query, cursor, filters }, host) {
      const parameters = searchParameters(filters);
      if (query.trim()) parameters.push(["title", query.trim()]);
      return mangaPage(host, cursor, parameters);
    },
    async getFeeds() {
      return [
        { id: "latest", title: "Latest updates" },
        { id: "popular", title: "Popular" },
        { id: "recent", title: "Recently added" }
      ];
    },
    async getFeedPage({ feedID, cursor, filters }, host) {
      const sort = feedID === "latest" ? "latestUploadedChapter" : feedID === "popular" ? "followedCount" : feedID === "recent" ? "createdAt" : null;
      if (!sort) throw new Error("Unknown MangaDex feed");
      return mangaPage(host, cursor, searchParameters(filters, `${sort}:desc`));
    },
    async getMangaDetails({ mangaID }, host) {
      uuid(mangaID);
      const response = await get(host, `/manga/${mangaID}`, [["includes[]", "cover_art"], ["includes[]", "author"], ["includes[]", "artist"]]);
      const manga = entity(response.data, "manga");
      if (manga.id !== mangaID) throw new Error("Manga ID mismatch");
      const attributes = object(manga.attributes);
      const names = (type) => relationships(manga).filter((item) => item.type === type && item.attributes != null).map((item) => text(object(item.attributes).name));
      const availableLanguages = attributes.availableTranslatedLanguages == null ? [language] : attributes.availableTranslatedLanguages.filter((value) => typeof value === "string" && /^[a-z-]{2,8}$/.test(value));
      const tags = attributes.tags == null ? [] : attributes.tags.map((value) => localized([object(object(object(value).attributes).name)], [language]) ?? "Tag");
      return {
        ...summary(manga),
        description: localized([object(attributes.description)], [language]) ?? "",
        authors: names("author"),
        artists: names("artist"),
        tags,
        status: optionalText(attributes.status),
        year: attributes.year == null ? null : String(integer(attributes.year)),
        availableLanguages: [...new Set(availableLanguages)].map((id) => ({ id, title: languages.find((option) => option.id === id)?.title ?? id })),
        defaultChapterLanguage: availableLanguages.includes(language) ? language : availableLanguages[0] ?? language,
        webURL: `https://mangadex.org/title/${mangaID}`
      };
    },
    async getChapterPage({ mangaID, cursor, language: selectedLanguage }, host) {
      uuid(mangaID);
      const chapterLanguage = selectedLanguage ?? language;
      if (!/^[a-z]{2}(-[a-z]{2,3})?$/.test(chapterLanguage)) throw new Error("Invalid chapter language");
      const offset = offsetFrom(cursor);
      const limit = Math.min(chapterPageSize, maximumResults - offset);
      const response = await get(host, `/manga/${mangaID}/feed`, [
        ["limit", String(limit)],
        ["offset", String(offset)],
        ["translatedLanguage[]", chapterLanguage],
        ["includes[]", "scanlation_group"],
        ["order[volume]", "asc"],
        ["order[chapter]", "asc"],
        ["order[createdAt]", "asc"],
        ["includeExternalUrl", "0"],
        ["includeUnavailable", "0"],
        ["includeEmptyPages", "0"],
        ["includeFutureUpdates", "0"],
        ["includeFuturePublishAt", "0"],
        ...["safe", "suggestive", "erotica", "pornographic"].map((value) => ["contentRating[]", value])
      ]);
      const page = collection(response, offset, limit);
      const items = page.items.map((value, index) => chapter(value, mangaID, offset + index, chapterLanguage)).filter((value) => value !== null);
      return { items: unique(items), nextCursor: page.nextCursor };
    },
    async getChapterPages({ mangaID, chapterID }, host) {
      uuid(mangaID);
      uuid(chapterID);
      const metadata = await get(host, `/chapter/${chapterID}`);
      if (object(metadata.data).id !== chapterID || chapter(metadata.data, mangaID, 0) === null) {
        throw new Error("Chapter is not readable");
      }
      const response = await get(host, `/at-home/server/${chapterID}`, [["forcePort443", "true"]]);
      const base = imageBase(response.baseUrl);
      const pages = object(response.chapter);
      const hash = segment(pages.hash);
      if (!Array.isArray(pages.data) || pages.data.length === 0 || pages.data.length > 2e3) {
        throw new Error("Missing chapter pages");
      }
      return pages.data.map((file, index) => ({
        id: `${chapterID}:${index + 1}`,
        url: `${base}/data/${hash}/${segment(file)}`,
        headers: { Referer: referer }
      }));
    }
  });
  return __toCommonJS(index_exports);
})();

"""#)
    ]
}
