// Generated by Extensions/scripts/build.mjs from reviewed bundled.json. Do not edit.
nonisolated enum BundledExtensionResources {
    static let entries: [(manifestJSON: String, javaScript: String)] = [
        (manifestJSON: #"""
{"id":"dev.midoku.mangadex","name":"MangaDex","version":"0.1.0","contractVersion":1,"domains":["api.mangadex.org","mangadex.org","uploads.mangadex.org","*.mangadex.network"],"capabilities":["search","feeds","details","chapters","pages"]}
"""#, javaScript: #"""
var MidokuExtension = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sources/dev.midoku.mangadex/index.ts
  var index_exports = {};
  __export(index_exports, {
    default: () => index_default
  });

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sdk/index.ts
  function defineExtension(extension) {
    return Object.freeze(extension);
  }

  // midoku:/Users/raahat/Projects/PracticeProjects/Midoku/Extensions/sources/dev.midoku.mangadex/index.ts
  var api = "https://api.mangadex.org";
  var referer = "https://mangadex.org/";
  var pageSize = 20;
  var chapterPageSize = 100;
  var maximumResults = 1e4;
  var language = "en";
  var ratings = [["contentRating[]", "safe"], ["contentRating[]", "suggestive"]];
  var uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
  function object(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected object");
    return value;
  }
  function text(value) {
    if (typeof value !== "string" || !value.trim()) throw new Error("Missing text");
    return value;
  }
  function optionalText(value) {
    if (value == null || value === "") return null;
    return text(value);
  }
  function integer(value) {
    if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) throw new Error("Invalid count");
    return value;
  }
  function uuid(value) {
    const id = text(value);
    if (!uuidPattern.test(id)) throw new Error("Invalid MangaDex ID");
    return id;
  }
  function segment(value) {
    const part = text(value);
    if (part === "." || part === ".." || /[\\/%?#\s]/.test(part)) throw new Error("Invalid resource path");
    return encodeURIComponent(part);
  }
  function offsetFrom(cursor) {
    if (cursor == null) return 0;
    if (!/^(0|[1-9][0-9]{0,3})$/.test(cursor)) throw new Error("Invalid MangaDex cursor");
    return Number(cursor);
  }
  function localized(maps, preferred) {
    for (const map of maps) {
      for (const value of Object.values(map)) {
        if (typeof value !== "string") throw new Error("Invalid localized text");
      }
    }
    for (const locale of preferred) {
      for (const map of maps) {
        const value = map[locale];
        if (typeof value === "string" && value.trim()) return value;
      }
    }
    for (const map of maps) {
      for (const locale of Object.keys(map).sort()) {
        const value = map[locale];
        if (value.trim()) return value;
      }
    }
    return null;
  }
  function relationships(value) {
    if (!Array.isArray(value.relationships)) throw new Error("Missing relationships");
    return value.relationships.map(object);
  }
  function entity(value, type) {
    const result = object(value);
    if (result.type !== type) throw new Error("Unexpected entity type");
    uuid(result.id);
    object(result.attributes);
    return result;
  }
  function summary(value) {
    const manga = entity(value, "manga");
    const attributes = object(manga.attributes);
    const maps = [object(attributes.title)];
    if (attributes.altTitles !== void 0) {
      if (!Array.isArray(attributes.altTitles)) throw new Error("Invalid alternative titles");
      maps.push(...attributes.altTitles.map(object));
    }
    const title = localized(maps, [language, "ja-ro", optionalText(attributes.originalLanguage) ?? ""]);
    if (!title) throw new Error("Missing manga title");
    const cover = relationships(manga).find((item) => item.type === "cover_art");
    const fileName = cover?.attributes == null ? null : optionalText(object(cover.attributes).fileName);
    const id = uuid(manga.id);
    return {
      id,
      title,
      coverURL: fileName === null ? null : `https://uploads.mangadex.org/covers/${id}/${segment(fileName)}.256.jpg`
    };
  }
  async function get(host, path, parameters = []) {
    const query = parameters.map(([key, value]) => encodeURIComponent(key) + "=" + encodeURIComponent(value)).join("&");
    const response = await host.request({
      url: api + path + (query ? "?" + query : ""),
      headers: { Accept: "application/json", Referer: referer }
    });
    const result = object(JSON.parse(response.body));
    if (result.result !== "ok") throw new Error("MangaDex returned an API error");
    return result;
  }
  function collection(value, offset, limit) {
    if (value.response !== "collection" || !Array.isArray(value.data)) throw new Error("Missing collection");
    const actualLimit = integer(value.limit);
    const total = integer(value.total);
    if (integer(value.offset) !== offset || actualLimit < 1 || actualLimit > limit || value.data.length > actualLimit) {
      throw new Error("Invalid pagination metadata");
    }
    if (value.data.length === 0 && offset < total) throw new Error("Unexpected empty page");
    const next = offset + actualLimit;
    return { items: value.data, nextCursor: next < Math.min(total, maximumResults) ? String(next) : null };
  }
  function unique(items) {
    if (new Set(items.map((item) => item.id)).size !== items.length) throw new Error("Duplicate source ID");
    return items;
  }
  async function mangaPage(host, cursor, parameters) {
    const offset = offsetFrom(cursor);
    const limit = Math.min(pageSize, maximumResults - offset);
    const response = await get(host, "/manga", [
      ["limit", String(limit)],
      ["offset", String(offset)],
      ["includes[]", "cover_art"],
      ["hasAvailableChapters", "true"],
      ["availableTranslatedLanguage[]", language],
      ...ratings,
      ...parameters
    ]);
    const page = collection(response, offset, limit);
    return { items: unique(page.items.map(summary)), nextCursor: page.nextCursor };
  }
  function chapter(value, mangaID, ordinal) {
    const entry = entity(value, "chapter");
    const attributes = object(entry.attributes);
    const parent = relationships(entry).find((item) => item.type === "manga");
    if (!parent || uuid(parent.id) !== mangaID) throw new Error("Chapter belongs to another manga");
    if (attributes.isUnavailable !== void 0 && typeof attributes.isUnavailable !== "boolean") {
      throw new Error("Invalid chapter availability");
    }
    if (optionalText(attributes.externalUrl) !== null || attributes.isUnavailable === true || integer(attributes.pages) === 0) return null;
    const translatedLanguage = text(attributes.translatedLanguage);
    if (translatedLanguage !== language) return null;
    const number = optionalText(attributes.chapter);
    const volume = optionalText(attributes.volume);
    const fallback = number === null ? "Oneshot" : `Chapter ${number}`;
    const title = optionalText(attributes.title) ?? fallback;
    return {
      id: uuid(entry.id),
      title: volume === null ? title : `Vol. ${volume} \xB7 ${title}`,
      number,
      ordinal,
      language: translatedLanguage
    };
  }
  function imageBase(value) {
    const base = text(value).replace(/\/$/, "");
    const match = /^https:\/\/([a-z0-9.-]+)(?::443)?((?:\/[A-Za-z0-9._~-]+)*)$/.exec(base);
    const host = match?.[1];
    if (!host || !(host === "uploads.mangadex.org" || host.endsWith(".mangadex.network"))) {
      throw new Error("Unexpected MangaDex image host");
    }
    if (match[2].split("/").some((part) => part === "." || part === "..")) throw new Error("Invalid image base path");
    return base;
  }
  var index_default = defineExtension({
    async search({ query, cursor }, host) {
      return mangaPage(host, cursor, [["title", query.trim()], ["order[relevance]", "desc"]]);
    },
    async getFeeds() {
      return [
        { id: "latest", title: "Latest updates" },
        { id: "popular", title: "Popular" },
        { id: "recent", title: "Recently added" }
      ];
    },
    async getFeedPage({ feedID, cursor }, host) {
      const sort = feedID === "latest" ? "latestUploadedChapter" : feedID === "popular" ? "followedCount" : feedID === "recent" ? "createdAt" : null;
      if (!sort) throw new Error("Unknown MangaDex feed");
      return mangaPage(host, cursor, [[`order[${sort}]`, "desc"]]);
    },
    async getMangaDetails({ mangaID }, host) {
      uuid(mangaID);
      const response = await get(host, `/manga/${mangaID}`, [["includes[]", "cover_art"]]);
      const manga = entity(response.data, "manga");
      if (manga.id !== mangaID) throw new Error("Manga ID mismatch");
      const attributes = object(manga.attributes);
      return { ...summary(manga), description: localized([object(attributes.description)], [language]) ?? "" };
    },
    async getChapterPage({ mangaID, cursor }, host) {
      uuid(mangaID);
      const offset = offsetFrom(cursor);
      const limit = Math.min(chapterPageSize, maximumResults - offset);
      const response = await get(host, `/manga/${mangaID}/feed`, [
        ["limit", String(limit)],
        ["offset", String(offset)],
        ["translatedLanguage[]", language],
        ["order[volume]", "asc"],
        ["order[chapter]", "asc"],
        ["order[createdAt]", "asc"],
        ["includeExternalUrl", "0"],
        ["includeUnavailable", "0"],
        ["includeEmptyPages", "0"],
        ["includeFutureUpdates", "0"],
        ["includeFuturePublishAt", "0"],
        ...ratings
      ]);
      const page = collection(response, offset, limit);
      const items = page.items.map((value, index) => chapter(value, mangaID, offset + index)).filter((value) => value !== null);
      return { items: unique(items), nextCursor: page.nextCursor };
    },
    async getChapterPages({ mangaID, chapterID }, host) {
      uuid(mangaID);
      uuid(chapterID);
      const metadata = await get(host, `/chapter/${chapterID}`);
      if (object(metadata.data).id !== chapterID || chapter(metadata.data, mangaID, 0) === null) {
        throw new Error("Chapter is not readable");
      }
      const response = await get(host, `/at-home/server/${chapterID}`, [["forcePort443", "true"]]);
      const base = imageBase(response.baseUrl);
      const pages = object(response.chapter);
      const hash = segment(pages.hash);
      if (!Array.isArray(pages.data) || pages.data.length === 0 || pages.data.length > 2e3) {
        throw new Error("Missing chapter pages");
      }
      return pages.data.map((file, index) => ({
        id: `${chapterID}:${index + 1}`,
        url: `${base}/data/${hash}/${segment(file)}`,
        headers: { Referer: referer }
      }));
    }
  });
  return __toCommonJS(index_exports);
})();

"""#)
    ]
}
